In [1]:
import numpy as np
import pandas as pd

from matplotlib import pyplot
import seaborn as sns

import numpy as np
import pandas as pd

# Data visualization
import matplotlib.pyplot as plt
from matplotlib import cm # Colomaps
import seaborn as sns

# Classifier algorithms
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

#train test split
from sklearn.model_selection import train_test_split

# Model evaluation
from sklearn import metrics
import tensorflow as tf

In [2]:
file_name = 'https://raw.githubusercontent.com/Pradeep-dev-ml/bank-markating/main/Data%20%20Set/bank-additional-full.csv'

# Load CSV File

data = pd.read_csv(file_name,'',';')
data.sample(20)

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
8943,40,technician,married,basic.9y,unknown,yes,no,telephone,jun,thu,...,2,999,0,nonexistent,1.4,94.465,-41.8,4.866,5228.1,no
9088,48,admin.,divorced,university.degree,no,no,no,telephone,jun,fri,...,4,999,0,nonexistent,1.4,94.465,-41.8,4.967,5228.1,no
24708,37,entrepreneur,married,basic.9y,unknown,no,no,telephone,nov,mon,...,1,999,0,nonexistent,-0.1,93.200,-42.0,4.191,5195.8,no
20593,41,technician,married,professional.course,no,yes,no,cellular,aug,tue,...,2,999,0,nonexistent,1.4,93.444,-36.1,4.966,5228.1,no
13213,30,blue-collar,married,high.school,unknown,yes,no,cellular,jul,wed,...,1,999,0,nonexistent,1.4,93.918,-42.7,4.962,5228.1,no
26779,47,blue-collar,married,basic.6y,no,yes,yes,cellular,nov,thu,...,6,999,0,nonexistent,-0.1,93.200,-42.0,4.076,5195.8,no
27041,50,blue-collar,married,university.degree,unknown,no,no,cellular,nov,fri,...,1,999,0,nonexistent,-0.1,93.200,-42.0,4.021,5195.8,no
20906,34,technician,married,university.degree,unknown,yes,no,cellular,aug,thu,...,1,999,0,nonexistent,1.4,93.444,-36.1,4.964,5228.1,no
14443,38,technician,single,professional.course,no,yes,no,cellular,jul,tue,...,2,999,0,nonexistent,1.4,93.918,-42.7,4.961,5228.1,no
24417,39,management,married,university.degree,no,no,no,cellular,nov,mon,...,1,999,1,failure,-0.1,93.200,-42.0,4.191,5195.8,no
19095,32,technician,single,university.degree,no,no,no,cellular,aug,tue,...,1,999,0,nonexistent,1.4,93.444,-36.1,4.968,5228.1,no
10297,36,technician,married,university.degree,no,no,no,telephone,jun,mon,...,1,999,0,nonexistent,1.4,94.465,-41.8,4.960,5228.1,yes
10027,53,technician,married,unknown,no,yes,no,telephone,jun,thu,...,3,999,0,nonexistent,1.4,94.465,-41.8,4.958,5228.1,no
17014,57,admin.,married,university.degree,no,yes,no,cellular,jul,thu,...,10,999,0,nonexistent,1.4,93.918,-42.7,4.962,5228.1,no
25228,32,admin.,single,university.degree,no,yes,no,cellular,nov,tue,...,2,999,1,failure,-0.1,93.200,-42.0,4.153,5195.8,no
12353,28,blue-collar,divorced,basic.4y,no,no,no,telephone,jul,fri,...,1,999,0,nonexistent,1.4,93.918,-42.7,4.959,5228.1,no
13526,23,blue-collar,single,basic.9y,no,no,no,cellular,jul,thu,...,1,999,0,nonexistent,1.4,93.918,-42.7,4.963,5228.1,no
29443,34,services,single,basic.6y,no,yes,no,cellular,apr,mon,...,1,999,0,nonexistent,-1.8,93.075,-47.1,1.405,5099.1,no
15601,33,admin.,single,university.degree,no,no,no,cellular,jul,mon,...,4,999,0,nonexistent,1.4,93.918,-42.7,4.960,5228.1,no
16892,53,blue-collar,married,unknown,no,no,yes,cellular,jul,thu,...,1,999,0,nonexistent,1.4,93.918,-42.7,4.962,5228.1,no

In [3]:


def pre_processing(data):
    data2=data
    dummy_column = pd.get_dummies(data2['job'], prefix='job', drop_first=False, dummy_na=False)
    data2=pd.concat([data2, dummy_column], join='outer', axis=1)
    
    dummy_column = pd.get_dummies(data2['education'], prefix='education', drop_first=False, dummy_na=False)
    data2=pd.concat([data2, dummy_column], join='outer', axis=1)
    
    dummy_column = pd.get_dummies(data2['marital'], prefix='marital', drop_first=False, dummy_na=False)
    data2=pd.concat([data2, dummy_column], join='outer', axis=1)
    
    data2['default'].value_counts()
    dummy_column = pd.get_dummies(data2['default'], prefix='default', drop_first=False, dummy_na=False)
    data2=pd.concat([data2, dummy_column], join='outer', axis=1)
    
    data2['housing'].value_counts().unique
    dummy_column = pd.get_dummies(data2['housing'], prefix='housing', drop_first=False, dummy_na=False)
    
    data2=pd.concat([data2, dummy_column], join='outer', axis=1)
    dummy_column = pd.get_dummies(data2['loan'], prefix='loan', drop_first=False, dummy_na=False)
    data2=pd.concat([data2, dummy_column], join='outer', axis=1)
    
    dummy_column = pd.get_dummies(data2['poutcome'], prefix='poutcome', drop_first=False, dummy_na=False)
    data2=pd.concat([data2, dummy_column], join='outer', axis=1)

    return data2

In [4]:

def model_train(model, model_name, X_train, y_train, X_test, y_test):
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    y_pred_prob = model.predict_proba(X_test)[:, 1]
    test_result = pd.DataFrame(data={'y_act':y_test, 'y_pred':y_pred, 'y_pred_prob':y_pred_prob})

    accuracy = metrics.accuracy_score(test_result['y_act'], test_result['y_pred']) 
    precision = metrics.precision_score(test_result['y_act'], test_result['y_pred'], average='binary',pos_label='yes')
    f1_score = metrics.f1_score(test_result['y_act'], test_result['y_pred'], average='weighted',)  #weighted accounts for label imbalance.
    roc_auc = metrics.roc_auc_score(test_result['y_act'], test_result['y_pred_prob'])

    return ({'model_name':model_name, 
                   'model':model, 
                   'accuracy':accuracy, 
                   'precision':precision,
                  'f1_score':f1_score,
                  'roc_auc':roc_auc,
                  })

In [6]:
TrainingDataFrame=pre_processing(data)

In [7]:
X=TrainingDataFrame[['age','duration', 'campaign', 'pdays',
       'previous', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed', 'job_admin.',
       'job_blue-collar', 'job_entrepreneur', 'job_housemaid',
       'job_management', 'job_retired', 'job_self-employed',
       'job_services', 'job_student', 'job_technician', 'job_unemployed',
       'job_unknown', 'education_basic.4y', 'education_basic.6y',
       'education_basic.9y', 'education_high.school',
       'education_illiterate', 'education_professional.course',
       'education_university.degree', 'education_unknown',
       'marital_divorced', 'marital_married', 'marital_single',
       'marital_unknown', 'default_no', 'default_unknown', 'default_yes',
       'housing_no', 'housing_unknown', 'housing_yes', 'loan_no',
       'loan_unknown', 'loan_yes', 'poutcome_failure',
       'poutcome_nonexistent', 'poutcome_success']]
Y=TrainingDataFrame['y']

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, Y,test_size=0.2,train_size=0.8, random_state=42)

In [9]:
model_train(LogisticRegression(max_iter=10000),'Logistic Regrassion',X_train,y_train, X_test,y_test)

{'model_name': 'Logistic Regrassion',
 'model': LogisticRegression(max_iter=10000),
 'accuracy': 0.9118718135469774,
 'precision': 0.6843033509700176,
 'f1_score': 0.9021587334788228,
 'roc_auc': 0.9288514499572001}

In [10]:

from sklearn.neighbors import KNeighborsClassifier
model_train(KNeighborsClassifier(n_neighbors=3),'Logistic Regrassion',X_train,y_train, X_test,y_test)

{'model_name': 'Logistic Regrassion',
 'model': KNeighborsClassifier(n_neighbors=3),
 'accuracy': 0.8954843408594318,
 'precision': 0.5463659147869674,
 'f1_score': 0.8918387762155449,
 'roc_auc': 0.8340758065142082}

In [11]:

from sklearn.neighbors import KNeighborsClassifier
model_train(KNeighborsClassifier(n_neighbors=6),'KNeighborsClassifier',X_train,y_train, X_test,y_test)

{'model_name': 'KNeighborsClassifier',
 'model': KNeighborsClassifier(n_neighbors=6),
 'accuracy': 0.9050740470988103,
 'precision': 0.6321243523316062,
 'f1_score': 0.8950429798349032,
 'roc_auc': 0.8796737257635678}

In [12]:

from sklearn.neighbors import KNeighborsClassifier
model_train(KNeighborsClassifier(n_neighbors=9),'Logistic Regrassion',X_train,y_train, X_test,y_test)

{'model_name': 'Logistic Regrassion',
 'model': KNeighborsClassifier(n_neighbors=9),
 'accuracy': 0.9068948773974266,
 'precision': 0.6141304347826086,
 'f1_score': 0.9019766477050184,
 'roc_auc': 0.8992025107255754}

In [13]:

from sklearn.neighbors import KNeighborsClassifier
model_train(KNeighborsClassifier(n_neighbors=30),'Logistic Regrassion',X_train,y_train, X_test,y_test)

{'model_name': 'Logistic Regrassion',
 'model': KNeighborsClassifier(n_neighbors=30),
 'accuracy': 0.9129643117261471,
 'precision': 0.6631736526946108,
 'f1_score': 0.906497094385472,
 'roc_auc': 0.92710482323212}

In [14]:

from sklearn.neighbors import KNeighborsClassifier
model_train(KNeighborsClassifier(n_neighbors=800),'Logistic Regrassion',X_train,y_train, X_test,y_test)

{'model_name': 'Logistic Regrassion',
 'model': KNeighborsClassifier(n_neighbors=800),
 'accuracy': 0.9019179412478757,
 'precision': 0.6104347826086957,
 'f1_score': 0.8914056988024234,
 'roc_auc': 0.9270841006662709}

In [15]:
from sklearn.tree import DecisionTreeClassifier
model_train(DecisionTreeClassifier(criterion='entropy', random_state=20),'DecisionTreeClassifier',X_train,y_train, X_test,y_test)

{'model_name': 'DecisionTreeClassifier',
 'model': DecisionTreeClassifier(criterion='entropy', random_state=20),
 'accuracy': 0.884316581694586,
 'precision': 0.49072164948453606,
 'f1_score': 0.8852403526582137,
 'roc_auc': 0.7207237374428939}

In [16]:
modelTest=LogisticRegression(max_iter=10000)
modelTest.fit(X_train, y_train)

LogisticRegression(max_iter=10000)

In [17]:
testdata=pre_processing(data)

In [20]:

X_test=testdata[['age','duration', 'campaign', 'pdays',
       'previous', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed', 'job_admin.',
       'job_blue-collar', 'job_entrepreneur', 'job_housemaid',
       'job_management', 'job_retired', 'job_self-employed',
       'job_services', 'job_student', 'job_technician', 'job_unemployed',
       'job_unknown', 'education_basic.4y', 'education_basic.6y',
       'education_basic.9y', 'education_high.school',
       'education_illiterate', 'education_professional.course',
       'education_university.degree', 'education_unknown',
       'marital_divorced', 'marital_married', 'marital_single',
       'marital_unknown', 'default_no', 'default_unknown', 'default_yes',
       'housing_no', 'housing_unknown', 'housing_yes', 'loan_no',
       'loan_unknown', 'loan_yes', 'poutcome_failure',
       'poutcome_nonexistent', 'poutcome_success']]

In [21]:
Y_Predicted = modelTest.predict(X_test)

In [24]:
test_result = pd.DataFrame(data={'y_act':testdata['y'],'y_predicted':Y_Predicted,'index_A':testdata.index})
test_result.head(100)

   y_act y_predicted  index_A
0     no          no        0
1     no          no        1
2     no          no        2
3     no          no        3
4     no          no        4
..   ...         ...      ...
95    no          no       95
96    no          no       96
97    no          no       97
98    no          no       98
99    no          no       99

[100 rows x 3 columns]

In [42]:
    wrong=[]
    for index, row in test_result.iterrows():
    
        if (row['y_act']!=row['y_predicted']):
            wrong.append(row['index_A'])

In [44]:
print(len(wrong))

3701

In [45]:
len(data)

41188

In [46]:
print(wrong)

[37, 129, 139, 164, 182, 199, 286, 504, 590, 719, 832, 840, 870, 876, 943, 981, 1001, 1077, 1113, 1166, 1189, 1305, 1319, 1348, 1367, 1501, 1538, 1608, 1613, 1632, 1636, 1655, 1689, 1691, 1725, 1763, 1766, 1819, 1839, 1852, 1853, 1906, 1984, 2000, 2002, 2039, 2064, 2076, 2105, 2132, 2257, 2294, 2305, 2313, 2315, 2316, 2367, 2406, 2421, 2424, 2444, 2449, 2465, 2473, 2575, 2624, 2629, 2635, 2654, 2684, 2697, 2713, 2755, 2775, 2779, 2853, 2905, 2929, 3040, 3083, 3090, 3113, 3144, 3183, 3210, 3219, 3223, 3259, 3261, 3264, 3338, 3381, 3407, 3453, 3506, 3541, 3545, 3564, 3566, 3570, 3608, 3628, 3661, 3677, 3693, 3697, 3740, 3765, 3807, 3822, 3823, 3829, 3855, 3887, 3891, 3892, 3939, 3979, 3988, 4034, 4049, 4050, 4110, 4164, 4167, 4213, 4294, 4397, 4410, 4420, 4485, 4522, 4526, 4623, 4635, 4672, 4677, 4694, 4700, 4720, 4737, 4752, 4769, 4793, 4836, 4851, 4872, 4899, 4901, 4904, 4982, 4993, 5007, 5027, 5056, 5081, 5084, 5107, 5112, 5162, 5174, 5273, 5329, 5347, 5363, 5384, 5386, 5442, 5467, 5550, 5597, 5613, 5619, 5636, 5638, 5652, 5707, 5731, 5780, 5784, 5818, 5850, 5852, 5863, 6018, 6104, 6143, 6164, 6203, 6213, 6264, 6320, 6362, 6394, 6406, 6466, 6520, 6573, 6585, 6605, 6629, 6648, 6662, 6678, 6695, 6762, 6803, 6860, 6901, 6928, 6937, 6959, 6982, 7009, 7095, 7099, 7162, 7201, 7216, 7266, 7289, 7297, 7359, 7397, 7404, 7419, 7437, 7444, 7445, 7470, 7475, 7478, 7542, 7544, 7558, 7571, 7620, 7652, 7717, 7719, 7725, 7731, 7760, 7793, 7808, 7811, 7814, 7817, 7819, 7835, 7881, 7952, 7983, 8014, 8016, 8062, 8102, 8112, 8130, 8135, 8180, 8196, 8233, 8246, 8276, 8279, 8315, 8350, 8355, 8360, 8379, 8417, 8482, 8502, 8528, 8535, 8542, 8554, 8568, 8596, 8599, 8603, 8607, 8621, 8661, 8804, 8817, 8826, 8866, 8883, 8897, 8906, 8912, 8958, 8977, 9003, 9028, 9101, 9150, 9157, 9160, 9196, 9203, 9204, 9205, 9215, 9239, 9256, 9258, 9338, 9346, 9365, 9447, 9471, 9524, 9547, 9572, 9585, 9636, 9650, 9705, 9708, 9733, 9741, 9792, 9796, 9811, 9840, 9841, 9852, 9901, 9904, 9907, 9911, 9914, 9998, 10034, 10049, 10076, 10124, 10134, 10144, 10157, 10160, 10162, 10227, 10239, 10247, 10310, 10329, 10332, 10402, 10418, 10544, 10635, 10658, 10661, 10663, 10666, 10685, 10704, 10790, 10825, 10835, 10848, 10893, 10914, 10916, 10936, 10977, 10979, 11016, 11017, 11020, 11046, 11070, 11100, 11145, 11172, 11233, 11241, 11255, 11274, 11317, 11345, 11346, 11348, 11360, 11417, 11444, 11449, 11450, 11471, 11473, 11492, 11535, 11552, 11564, 11567, 11690, 11708, 11716, 11717, 11737, 11752, 11790, 11931, 11933, 11936, 11937, 11947, 11961, 12002, 12004, 12023, 12039, 12041, 12057, 12133, 12139, 12187, 12191, 12195, 12264, 12322, 12349, 12384, 12385, 12387, 12404, 12425, 12455, 12458, 12461, 12466, 12501, 12506, 12526, 12565, 12568, 12573, 12586, 12596, 12605, 12707, 12758, 12766, 12767, 12785, 12803, 12806, 12809, 12823, 12826, 12843, 12866, 12878, 12887, 12904, 12931, 12932, 12971, 12979, 12982, 12983, 13011, 13016, 13031, 13120, 13129, 13131, 13134, 13176, 13186, 13189, 13217, 13218, 13223, 13224, 13231, 13258, 13269, 13276, 13281, 13284, 13293, 13359, 13409, 13431, 13460, 13494, 13504, 13518, 13531, 13542, 13551, 13585, 13595, 13620, 13627, 13685, 13700, 13705, 13710, 13726, 13727, 13732, 13734, 13792, 13799, 13807, 13834, 13836, 13882, 13891, 13925, 13942, 13977, 13978, 13983, 14000, 14002, 14029, 14050, 14054, 14067, 14069, 14076, 14103, 14137, 14177, 14220, 14222, 14236, 14262, 14278, 14341, 14356, 14382, 14410, 14424, 14465, 14477, 14479, 14482, 14492, 14520, 14554, 14576, 14582, 14591, 14592, 14596, 14597, 14598, 14618, 14633, 14639, 14684, 14686, 14695, 14711, 14712, 14722, 14729, 14740, 14746, 14755, 14787, 14788, 14789, 14795, 14803, 14805, 14813, 14815, 14821, 14828, 14864, 14871, 14879, 14884, 14888, 14892, 14909, 14919, 14944, 14948, 14955, 14962, 15010, 15045, 15058, 15110, 15121, 15126, 15128, 15155, 15190, 15194, 15197, 15209, 15210, 15211, 15215, 15255, 15269, 15294, 15316, 15317, 15319, 15344, 15345, 15346, 15353, 15357, 15368, 15378, 15387, 15394, 15403, 15410, 15429, 15450, 15452, 15456, 15474, 15478, 15485, 15489, 15498, 15500, 15512, 15514, 15564, 15581, 15586, 15613, 15629, 15642, 15663, 15710, 15725, 15744, 15757, 15761, 15762, 15771, 15776, 15782, 15787, 15791, 15793, 15799, 15810, 15822, 15866, 15877, 15891, 15912, 15925, 15938, 15951, 15994, 16031, 16045, 16056, 16058, 16133, 16135, 16149, 16161, 16165, 16166, 16198, 16234, 16253, 16254, 16273, 16317, 16322, 16326, 16337, 16341, 16391, 16392, 16430, 16437, 16451, 16522, 16537, 16560, 16591, 16592, 16603, 16621, 16639, 16656, 16658, 16667, 16683, 16695, 16706, 16711, 16722, 16737, 16792, 16832, 16867, 16917, 16920, 16927, 16937, 16957, 16960, 16998, 17009, 17012, 17034, 17070, 17074, 17083, 17088, 17090, 17093, 17109, 17160, 17181, 17216, 17244, 17245, 17264, 17274, 17275, 17291, 17296, 17313, 17359, 17364, 17365, 17372, 17377, 17382, 17391, 17399, 17418, 17451, 17456, 17460, 17499, 17509, 17524, 17532, 17538, 17551, 17571, 17607, 17639, 17655, 17720, 17723, 17732, 17749, 17757, 17762, 17860, 17861, 17871, 17918, 17920, 17934, 17944, 18027, 18031, 18041, 18052, 18114, 18116, 18129, 18150, 18154, 18171, 18184, 18195, 18224, 18255, 18260, 18278, 18280, 18288, 18305, 18317, 18326, 18331, 18374, 18386, 18394, 18395, 18456, 18485, 18514, 18515, 18553, 18568, 18570, 18602, 18627, 18845, 18986, 19000, 19001, 19005, 19010, 19011, 19018, 19024, 19044, 19060, 19097, 19108, 19115, 19121, 19154, 19155, 19169, 19184, 19199, 19205, 19209, 19222, 19238, 19245, 19248, 19253, 19276, 19281, 19302, 19313, 19323, 19372, 19378, 19400, 19437, 19472, 19475, 19483, 19502, 19512, 19514, 19518, 19528, 19529, 19605, 19632, 19645, 19657, 19670, 19682, 19699, 19717, 19748, 19753, 19810, 19820, 19826, 19862, 19868, 19894, 19926, 19932, 19950, 19954, 19967, 19969, 19974, 19998, 20014, 20036, 20080, 20091, 20109, 20124, 20151, 20173, 20178, 20187, 20195, 20211, 20213, 20234, 20258, 20289, 20296, 20306, 20308, 20325, 20333, 20343, 20368, 20395, 20413, 20426, 20438, 20451, 20495, 20500, 20513, 20522, 20524, 20526, 20542, 20549, 20569, 20579, 20581, 20591, 20626, 20629, 20631, 20632, 20638, 20664, 20707, 20715, 20722, 20723, 20731, 20733, 20742, 20750, 20773, 20779, 20783, 20863, 20911, 20918, 20924, 20967, 20975, 20995, 20996, 21002, 21004, 21011, 21043, 21066, 21067, 21097, 21100, 21102, 21103, 21105, 21112, 21113, 21133, 21147, 21194, 21226, 21274, 21285, 21307, 21322, 21329, 21330, 21353, 21396, 21541, 21548, 21562, 21645, 21715, 21747, 21757, 21761, 21783, 21836, 21847, 21853, 21871, 21879, 21882, 21912, 21931, 21950, 21952, 21991, 21998, 22014, 22045, 22060, 22097, 22170, 22198, 22220, 22236, 22267, 22290, 22324, 22355, 22390, 22420, 22421, 22423, 22425, 22432, 22452, 22487, 22522, 22536, 22552, 22557, 22705, 22714, 22726, 22755, 22764, 22783, 22786, 22804, 22840, 22859, 22904, 22936, 22964, 22998, 23015, 23019, 23020, 23032, 23160, 23235, 23251, 23257, 23267, 23295, 23305, 23330, 23332, 23357, 23360, 23388, 23477, 23504, 23510, 23569, 23577, 23580, 23759, 23998, 23999, 24000, 24001, 24004, 24005, 24008, 24009, 24011, 24014, 24015, 24016, 24017, 24019, 24022, 24024, 24025, 24027, 24028, 24029, 24031, 24032, 24033, 24035, 24037, 24038, 24040, 24042, 24043, 24044, 24046, 24047, 24048, 24049, 24050, 24051, 24053, 24055, 24056, 24057, 24058, 24059, 24061, 24062, 24068, 24072, 24073, 24075, 24078, 24079, 24080, 24083, 24085, 24087, 24088, 24090, 24091, 24094, 24096, 24100, 24101, 24102, 24103, 24115, 24116, 24118, 24119, 24121, 24214, 24297, 24308, 24316, 24327, 24379, 24402, 24403, 24473, 24488, 24502, 24550, 24583, 24610, 24641, 24705, 24723, 24737, 24792, 24851, 24888, 24902, 24928, 24930, 24938, 24944, 24984, 25302, 25314, 25340, 25369, 25408, 25410, 25447, 25449, 25519, 25528, 25529, 25557, 25566, 25567, 25579, 25637, 25654, 25673, 25686, 25692, 25714, 25717, 25721, 25731, 25787, 25830, 25832, 25853, 25892, 25908, 25931, 25933, 25952, 25962, 25981, 26016, 26017, 26041, 26047, 26060, 26082, 26085, 26119, 26170, 26244, 26246, 26265, 26273, 26310, 26317, 26324, 26336, 26340, 26342, 26356, 26359, 26373, 26379, 26394, 26398, 26411, 26441, 26465, 26470, 26488, 26511, 26515, 26523, 26538, 26548, 26575, 26590, 26606, 26622, 26634, 26657, 26673, 26676, 26678, 26689, 26692, 26767, 26774, 26775, 26849, 26877, 26892, 26927, 26933, 26947, 26976, 26985, 26998, 27045, 27047, 27050, 27054, 27060, 27081, 27082, 27083, 27085, 27099, 27101, 27103, 27104, 27134, 27151, 27154, 27160, 27161, 27178, 27181, 27188, 27236, 27250, 27282, 27288, 27366, 27374, 27408, 27419, 27430, 27465, 27469, 27496, 27522, 27541, 27569, 27572, 27590, 27599, 27660, 27689, 27690, 27691, 27697, 27698, 27700, 27704, 27707, 27708, 27713, 27716, 27717, 27718, 27721, 27723, 27725, 27726, 27729, 27730, 27731, 27732, 27733, 27734, 27736, 27737, 27738, 27742, 27746, 27748, 27751, 27753, 27754, 27758, 27759, 27760, 27763, 27764, 27765, 27766, 27767, 27768, 27769, 27772, 27778, 27781, 27782, 27784, 27787, 27789, 27790, 27795, 27797, 27802, 27803, 27807, 27810, 27811, 27813, 27816, 27817, 27818, 27821, 27822, 27823, 27824, 27825, 27827, 27832, 27836, 27846, 27849, 27850, 27851, 27852, 27853, 27855, 27856, 27862, 27863, 27864, 27866, 27867, 27868, 27870, 27873, 27874, 27876, 27878, 27880, 27883, 27888, 27890, 27891, 27892, 27893, 27895, 27896, 27897, 27898, 27901, 27904, 27911, 27916, 27917, 27918, 27919, 27921, 27923, 27925, 27930, 27931, 27932, 27934, 27937, 27941, 27942, 27943, 27945, 27952, 27953, 27955, 27958, 27962, 27963, 27969, 27973, 27988, 27991, 27994, 28003, 28010, 28012, 28017, 28022, 28038, 28040, 28046, 28054, 28068, 28083, 28085, 28100, 28108, 28123, 28131, 28132, 28136, 28166, 28177, 28182, 28183, 28192, 28214, 28222, 28223, 28228, 28260, 28261, 28278, 28287, 28296, 28297, 28305, 28308, 28312, 28315, 28338, 28347, 28348, 28352, 28354, 28356, 28357, 28367, 28373, 28378, 28380, 28385, 28387, 28400, 28404, 28406, 28407, 28413, 28417, 28418, 28423, 28431, 28433, 28437, 28449, 28456, 28460, 28467, 28468, 28469, 28470, 28482, 28484, 28486, 28488, 28489, 28495, 28498, 28499, 28502, 28506, 28507, 28508, 28511, 28513, 28519, 28520, 28521, 28530, 28534, 28538, 28540, 28544, 28546, 28549, 28574, 28579, 28581, 28582, 28587, 28589, 28591, 28593, 28595, 28598, 28599, 28601, 28614, 28622, 28624, 28625, 28628, 28629, 28632, 28633, 28635, 28641, 28679, 28701, 28714, 28717, 28723, 28724, 28732, 28743, 28750, 28752, 28766, 28781, 28803, 28814, 28820, 28826, 28831, 28833, 28839, 28841, 28858, 28865, 28867, 28869, 28873, 28902, 28943, 28979, 28992, 29002, 29024, 29051, 29052, 29053, 29068, 29080, 29094, 29116, 29126, 29132, 29155, 29157, 29165, 29180, 29186, 29202, 29203, 29208, 29210, 29218, 29225, 29233, 29239, 29255, 29265, 29276, 29278, 29280, 29282, 29294, 29312, 29316, 29319, 29323, 29329, 29335, 29345, 29346, 29348, 29352, 29363, 29371, 29372, 29374, 29376, 29383, 29384, 29393, 29401, 29407, 29410, 29451, 29512, 29520, 29523, 29532, 29557, 29562, 29566, 29588, 29609, 29610, 29644, 29649, 29651, 29668, 29676, 29682, 29707, 29711, 29726, 29735, 29739, 29741, 29747, 29748, 29750, 29767, 29771, 29779, 29795, 29808, 29819, 29823, 29826, 29833, 29859, 29951, 29957, 29969, 29970, 29971, 29972, 29977, 29979, 29980, 29981, 29985, 29986, 29988, 29989, 29994, 29998, 29999, 30000, 30001, 30003, 30004, 30005, 30006, 30007, 30008, 30017, 30018, 30020, 30021, 30023, 30025, 30027, 30028, 30030, 30031, 30032, 30033, 30034, 30036, 30039, 30040, 30041, 30045, 30047, 30048, 30049, 30050, 30055, 30056, 30058, 30059, 30060, 30063, 30065, 30069, 30076, 30082, 30083, 30089, 30092, 30096, 30097, 30101, 30105, 30112, 30118, 30119, 30132, 30133, 30134, 30135, 30140, 30141, 30143, 30146, 30157, 30158, 30167, 30168, 30172, 30176, 30177, 30179, 30180, 30183, 30184, 30186, 30189, 30190, 30194, 30195, 30197, 30198, 30202, 30203, 30207, 30209, 30210, 30212, 30215, 30217, 30218, 30220, 30222, 30223, 30230, 30231, 30233, 30234, 30235, 30236, 30243, 30247, 30252, 30253, 30268, 30270, 30273, 30274, 30277, 30282, 30284, 30286, 30288, 30289, 30291, 30292, 30297, 30301, 30302, 30309, 30311, 30312, 30316, 30319, 30321, 30322, 30323, 30326, 30329, 30336, 30339, 30342, 30343, 30345, 30356, 30357, 30360, 30361, 30362, 30365, 30368, 30372, 30383, 30389, 30393, 30397, 30399, 30401, 30403, 30404, 30411, 30414, 30421, 30422, 30423, 30428, 30429, 30434, 30436, 30437, 30439, 30441, 30448, 30450, 30451, 30454, 30458, 30459, 30461, 30464, 30468, 30471, 30472, 30487, 30490, 30493, 30496, 30497, 30501, 30502, 30516, 30529, 30542, 30544, 30555, 30565, 30580, 30581, 30585, 30586, 30589, 30591, 30593, 30595, 30599, 30609, 30610, 30614, 30619, 30621, 30632, 30635, 30644, 30679, 30721, 30723, 30732, 30734, 30769, 30786, 30843, 30844, 30887, 30932, 30942, 30965, 30977, 30980, 30992, 31011, 31039, 31053, 31064, 31089, 31121, 31139, 31163, 31165, 31180, 31206, 31220, 31241, 31292, 31298, 31304, 31307, 31310, 31322, 31332, 31343, 31364, 31365, 31367, 31404, 31407, 31417, 31436, 31477, 31484, 31509, 31510, 31517, 31520, 31521, 31572, 31608, 31632, 31649, 31658, 31675, 31700, 31702, 31705, 31774, 31791, 31806, 31816, 31867, 31874, 31896, 31914, 31922, 31950, 31953, 31989, 32007, 32010, 32032, 32034, 32038, 32048, 32049, 32059, 32082, 32093, 32117, 32138, 32181, 32187, 32191, 32208, 32210, 32226, 32250, 32258, 32272, 32300, 32328, 32348, 32349, 32351, 32382, 32391, 32484, 32500, 32503, 32513, 32546, 32639, 32645, 32654, 32690, 32711, 32730, 32731, 32789, 32790, 32805, 32814, 32827, 32830, 32862, 32863, 32872, 32937, 32949, 33022, 33035, 33050, 33071, 33080, 33093, 33124, 33129, 33154, 33172, 33177, 33178, 33179, 33191, 33200, 33215, 33217, 33294, 33300, 33302, 33320, 33331, 33332, 33382, 33425, 33433, 33444, 33445, 33452, 33453, 33468, 33477, 33479, 33491, 33503, 33564, 33605, 33608, 33615, 33621, 33631, 33666, 33704, 33719, 33730, 33746, 33747, 33752, 33753, 33760, 33773, 33775, 33780, 33789, 33798, 33818, 33833, 33839, 33845, 33884, 33908, 33913, 33916, 33939, 33972, 33982, 33983, 33997, 34001, 34002, 34018, 34022, 34025, 34034, 34070, 34119, 34121, 34131, 34136, 34138, 34144, 34165, 34202, 34203, 34204, 34205, 34213, 34218, 34247, 34287, 34288, 34301, 34311, 34315, 34364, 34375, 34382, 34384, 34389, 34399, 34405, 34417, 34420, 34425, 34433, 34454, 34465, 34489, 34502, 34506, 34535, 34575, 34601, 34610, 34611, 34614, 34620, 34675, 34704, 34718, 34737, 34743, 34744, 34800, 34827, 34838, 34840, 34860, 34861, 34876, 34878, 34887, 34901, 34903, 34906, 34915, 34933, 34996, 35010, 35017, 35024, 35036, 35049, 35068, 35072, 35081, 35082, 35093, 35097, 35106, 35126, 35130, 35139, 35143, 35155, 35156, 35167, 35171, 35174, 35181, 35182, 35183, 35221, 35251, 35260, 35281, 35332, 35352, 35362, 35371, 35384, 35395, 35409, 35433, 35440, 35497, 35506, 35552, 35554, 35564, 35606, 35607, 35614, 35617, 35620, 35630, 35634, 35652, 35663, 35664, 35675, 35735, 35743, 35754, 35755, 35772, 35793, 35807, 35825, 35827, 35828, 35829, 35832, 35833, 35837, 35838, 35843, 35855, 35858, 35868, 35871, 35873, 35874, 35880, 35882, 35883, 35884, 35889, 35892, 35896, 35901, 35912, 35913, 35914, 35920, 35924, 35933, 35939, 35944, 35948, 35956, 35964, 35969, 35970, 35972, 35973, 35979, 35981, 35984, 35985, 35991, 35999, 36010, 36013, 36023, 36028, 36033, 36034, 36038, 36043, 36061, 36062, 36063, 36069, 36074, 36085, 36087, 36088, 36089, 36092, 36109, 36110, 36111, 36116, 36123, 36124, 36129, 36134, 36146, 36151, 36152, 36156, 36157, 36160, 36164, 36166, 36169, 36177, 36181, 36182, 36189, 36194, 36214, 36225, 36229, 36233, 36234, 36235, 36237, 36240, 36241, 36245, 36248, 36249, 36250, 36254, 36256, 36258, 36267, 36268, 36269, 36278, 36289, 36291, 36295, 36297, 36299, 36300, 36301, 36302, 36316, 36321, 36325, 36328, 36329, 36330, 36333, 36334, 36336, 36338, 36347, 36352, 36360, 36362, 36363, 36364, 36368, 36369, 36371, 36375, 36378, 36386, 36391, 36404, 36407, 36410, 36411, 36412, 36413, 36416, 36418, 36423, 36432, 36439, 36440, 36445, 36448, 36451, 36453, 36457, 36460, 36461, 36462, 36464, 36467, 36468, 36469, 36470, 36471, 36474, 36479, 36483, 36485, 36486, 36487, 36490, 36491, 36493, 36495, 36499, 36501, 36504, 36506, 36510, 36512, 36515, 36517, 36518, 36528, 36539, 36541, 36548, 36551, 36554, 36560, 36562, 36569, 36577, 36579, 36584, 36585, 36586, 36589, 36591, 36593, 36595, 36597, 36598, 36600, 36602, 36604, 36607, 36608, 36611, 36612, 36613, 36614, 36616, 36617, 36618, 36619, 36621, 36622, 36634, 36636, 36637, 36641, 36645, 36651, 36652, 36654, 36659, 36661, 36662, 36666, 36671, 36672, 36673, 36676, 36681, 36683, 36687, 36689, 36691, 36696, 36699, 36703, 36705, 36707, 36708, 36709, 36715, 36717, 36721, 36722, 36723, 36724, 36726, 36738, 36739, 36742, 36743, 36744, 36747, 36748, 36749, 36751, 36756, 36758, 36759, 36762, 36763, 36765, 36769, 36770, 36772, 36775, 36776, 36777, 36778, 36789, 36794, 36796, 36799, 36804, 36805, 36807, 36809, 36813, 36816, 36819, 36820, 36822, 36824, 36825, 36827, 36838, 36843, 36847, 36849, 36850, 36852, 36856, 36867, 36869, 36870, 36871, 36873, 36878, 36883, 36887, 36890, 36891, 36894, 36895, 36899, 36910, 36912, 36917, 36924, 36934, 36937, 36938, 36939, 36940, 36944, 36945, 36946, 36950, 36951, 36952, 36953, 36954, 36955, 36959, 36960, 36974, 36975, 36978, 36979, 36980, 36981, 36982, 36983, 36985, 36988, 36990, 36991, 36992, 36993, 36995, 37002, 37005, 37008, 37009, 37010, 37012, 37013, 37017, 37019, 37024, 37027, 37031, 37038, 37040, 37042, 37043, 37045, 37047, 37049, 37056, 37068, 37070, 37071, 37073, 37075, 37078, 37080, 37086, 37094, 37108, 37109, 37122, 37124, 37126, 37133, 37140, 37141, 37143, 37145, 37147, 37152, 37155, 37156, 37157, 37160, 37161, 37162, 37163, 37165, 37189, 37191, 37196, 37197, 37198, 37199, 37203, 37204, 37205, 37207, 37209, 37214, 37218, 37220, 37223, 37225, 37229, 37230, 37231, 37234, 37235, 37237, 37249, 37250, 37251, 37254, 37258, 37259, 37260, 37262, 37263, 37264, 37265, 37270, 37272, 37277, 37280, 37282, 37283, 37286, 37289, 37290, 37292, 37293, 37302, 37304, 37310, 37328, 37331, 37332, 37336, 37338, 37339, 37340, 37341, 37343, 37345, 37352, 37353, 37355, 37360, 37362, 37363, 37364, 37368, 37374, 37382, 37384, 37385, 37388, 37395, 37400, 37403, 37408, 37409, 37410, 37411, 37414, 37416, 37417, 37418, 37419, 37421, 37430, 37439, 37450, 37452, 37453, 37462, 37463, 37466, 37467, 37470, 37477, 37478, 37480, 37482, 37483, 37489, 37492, 37493, 37498, 37507, 37509, 37510, 37535, 37536, 37538, 37540, 37543, 37544, 37550, 37559, 37565, 37566, 37568, 37569, 37570, 37571, 37572, 37573, 37575, 37577, 37578, 37579, 37581, 37582, 37588, 37594, 37602, 37603, 37604, 37606, 37609, 37613, 37614, 37622, 37626, 37631, 37635, 37637, 37639, 37640, 37645, 37649, 37650, 37658, 37661, 37664, 37665, 37666, 37667, 37671, 37677, 37681, 37683, 37686, 37688, 37690, 37693, 37695, 37696, 37702, 37706, 37710, 37711, 37713, 37720, 37723, 37726, 37727, 37730, 37737, 37743, 37745, 37751, 37753, 37755, 37756, 37757, 37758, 37761, 37762, 37770, 37775, 37783, 37788, 37790, 37798, 37800, 37801, 37809, 37811, 37813, 37816, 37818, 37826, 37829, 37830, 37833, 37834, 37842, 37850, 37854, 37855, 37860, 37861, 37863, 37870, 37878, 37882, 37893, 37896, 37898, 37900, 37903, 37904, 37905, 37910, 37911, 37914, 37915, 37918, 37922, 37927, 37929, 37930, 37931, 37935, 37943, 37945, 37946, 37964, 37967, 37971, 37972, 37975, 37980, 37982, 37983, 37986, 37992, 37994, 37995, 37997, 38001, 38005, 38006, 38009, 38011, 38012, 38015, 38020, 38022, 38026, 38027, 38028, 38030, 38036, 38040, 38042, 38050, 38051, 38055, 38057, 38058, 38061, 38067, 38069, 38079, 38080, 38086, 38087, 38088, 38094, 38095, 38098, 38102, 38105, 38108, 38110, 38115, 38116, 38120, 38124, 38128, 38129, 38136, 38137, 38141, 38146, 38150, 38151, 38153, 38157, 38159, 38165, 38166, 38175, 38180, 38182, 38184, 38189, 38190, 38192, 38197, 38202, 38203, 38205, 38209, 38211, 38213, 38219, 38222, 38232, 38233, 38237, 38238, 38240, 38242, 38244, 38247, 38250, 38258, 38260, 38261, 38272, 38273, 38275, 38276, 38278, 38282, 38287, 38288, 38289, 38291, 38296, 38298, 38307, 38308, 38314, 38318, 38323, 38324, 383

In [51]:
testdata.iloc[37]

0

In [52]:
Filter_df  = testdata[testdata.index.isin(wrong)]

In [53]:
Filter_df.head(100)

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,default_yes,housing_no,housing_unknown,housing_yes,loan_no,loan_unknown,loan_yes,poutcome_failure,poutcome_nonexistent,poutcome_success
37,52,technician,married,basic.9y,no,yes,no,telephone,may,mon,...,0,0,0,1,1,0,0,0,1,0
129,41,technician,married,professional.course,unknown,yes,no,telephone,may,mon,...,0,0,0,1,1,0,0,0,1,0
139,45,blue-collar,married,basic.9y,unknown,yes,no,telephone,may,mon,...,0,0,0,1,1,0,0,0,1,0
164,39,services,divorced,high.school,unknown,no,no,telephone,may,mon,...,0,1,0,0,1,0,0,0,1,0
182,42,blue-collar,married,basic.9y,no,yes,yes,telephone,may,mon,...,0,0,0,1,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3541,45,entrepreneur,married,university.degree,no,yes,yes,telephone,may,fri,...,0,0,0,1,0,0,1,0,1,0
3545,35,admin.,single,high.school,no,no,yes,telephone,may,fri,...,0,1,0,0,0,0,1,0,1,0
3564,29,blue-collar,single,high.school,no,yes,no,telephone,may,fri,...,0,0,0,1,1,0,0,0,1,0
3566,44,management,single,university.degree,unknown,yes,no,telephone,may,fri,...,0,0,0,1,1,0,0,0,1,0
3570,31,blue-collar,married,basic.6y,unknown,unknown,unknown,telephone,may,fri,...,0,0,1,0,0,1,0,0,1,0